micronaut:
  application:
    name: demo
config:
  stuff:
    partner:
      stuffUser: stuffUser
      stuffUrl: ${PARTNER_STUFF_URL:defaultPartnerUrl}
    customer:
      stuffUser: stuffUser
      stuffUrl: ${CUSTOMER_STUFF_URL:defaultCustomerUrl}
